// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Describes the infrastructure at a given location.
 *
 * - describeInfrastructure - A function that describes the infrastructure.
 * - DescribeInfrastructureInput - The input type for the describeInfrastructure function.
 * - DescribeInfrastructureOutput - The return type for the describeInfrastructure function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DescribeInfrastructureInputSchema = z.object({
  latitude: z.number().describe('The latitude of the infrastructure element.'),
  longitude: z.number().describe('The longitude of the infrastructure element.'),
});
export type DescribeInfrastructureInput = z.infer<typeof DescribeInfrastructureInputSchema>;

const DescribeInfrastructureOutputSchema = z.object({
  description: z.string().describe('A description of the infrastructure element and its surrounding area.'),
});
export type DescribeInfrastructureOutput = z.infer<typeof DescribeInfrastructureOutputSchema>;

export async function describeInfrastructure(input: DescribeInfrastructureInput): Promise<DescribeInfrastructureOutput> {
  return describeInfrastructureFlow(input);
}

const prompt = ai.definePrompt({
  name: 'describeInfrastructurePrompt',
  input: {schema: DescribeInfrastructureInputSchema},
  output: {schema: DescribeInfrastructureOutputSchema},
  prompt: `You are an expert in real estate and industrial infrastructure.
  You will be provided with the coordinates of a location. You will generate a description of the infrastructure element at that location and its surrounding area, including its potential industrial significance.

  Latitude: {{latitude}}
  Longitude: {{longitude}}`,
});

const describeInfrastructureFlow = ai.defineFlow(
  {
    name: 'describeInfrastructureFlow',
    inputSchema: DescribeInfrastructureInputSchema,
    outputSchema: DescribeInfrastructureOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
